### ISSUE TITLE
Sponsors don't fit on anything smaller than desktop layout

### ISSUE THREAD

**Issue by mrmurphy** [elmtown/elmtown.github.io#10]

**Comment by elliotdavies** [comment]
@splodingsocks Are you open to a PR if I look into tweaking the CSS to fix this (plus anything else that doesn't fit on mobile)? I like to listen on my phone, so bump into this a lot.

**Comment by mrmurphy** [comment]
Absolutely! I'm sorry it's not better for you already. Lots going on at the moment 😊. A PR would be very very helpful.
