### ISSUE TITLE
Add feed to stitcher

### ISSUE THREAD

**Issue by amsross** [elmtown/elmtown.github.io#16]
Unfortunately, a user can't add a custom feed. Content providers must supply a feed to stitcher, then users can subscribe to it. 

Stitcher reads rss, rather than xml.

http://www.stitcher.com/content-faq

**Comment by amsross** [comment]
"rather" probably isn't the right word

**Comment by mrmurphy** [comment]
Hi, @amsross! I just checked it out and I'm not sure I'm ready to accept Stitcher's terms yet. When adding a podcast they claim the right to have the podcast producer mention the show on-air, and do other things to promote Stitcher. There may be a time in the future when we're ready for that, but not at the moment.

Thanks!

**Comment by amsross** [comment]
Understandable. Thanks for looking into it!
